spring:
  devtools:
    restart:
      additional-exclude: "**/*.log"
    livereload:
      enabled: false
  datasource1:
    url: jdbc:mysql://192.168.2.253:3306/koss_dev?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
    username: root
    password: Admin123
    driverClassName: com.mysql.jdbc.Driver
#    druid:
#      initial-size: 1
#      min-idle: 1
#      max-active: 20
#      test-on-borrow: true
#      stat-view-servlet:
#        allow: true
  datasource2:
    url: jdbc:mysql://192.168.2.253:3306/koss_2?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
    username: root
    password: Admin123
    driverClassName: com.mysql.jdbc.Driver
#    druid:
#      initial-size: 1
#      min-idle: 1
#      max-active: 20
#      test-on-borrow: true
#      stat-view-servlet:
#        allow: true
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*Mapper.xml
  type-aliases-package: org.fangsj.learn.spring.boot.jta.domain
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0
      db-type: mysql
      field-strategy: not_empty
      column-underline: true
  configuration:
    map-underscore-to-camel-case: true
    jdbc-type-for-null: null
logging:
  level:
    com: debug
    org.fangsj: debug